[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

# La placa tiene Flash Quad de 8 MB y PSRAM Octal embebida de 8 MB.
board_upload.maximum_size = 8388608
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

# Solo la PSRAM usa Octal; la Flash permanece en Quad para respetar el eFuse.
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.flash_mode = qio

lib_deps = 
    espressif/esp32-camera @ ^2.0.4
    links2004/WebSockets @ ^2.4.1

build_flags = 
    -DBOARD_HAS_PSRAM
    -DBOARD_HAS_PSRAM_OPI
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_MSC_ON_BOOT=0
    -DARDUINO_USB_DFU_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=3
    # Aumentar el búfer de envío del cliente WebSocket para evitar descartar frames JPEG de 20KB+
    -DWEBSOCKETS_MAX_HEADER_SIZE=14